#!/bin/bash

LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -listen -localhost no -depth 24 -name remote-desktop -SecurityTypes none --I-KNOW-THIS-IS-INSECURE -AcceptSetDesktopSize=0 $GEO :$PORT
echo "VNC server started. The default password is the account password for $USER"
